on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name"
        default: "Mehak"
        required: true
      city:
        description: "City"
        default: "Baraut"
        required: true
      country:
        default: "India"
        required: true

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello ${{ github.event.inputs.name }}"
      - name: List files
        run: ls -la
      - name: Checkout
        run: actions/checkout@v4
      - name: List files
        run: ls -la
